# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2B2220)
$foreground = rgb(F4EEE5)
$color0 = rgb(514845)
$color1 = rgb(2F120C)
$color2 = rgb(373430)
$color3 = rgb(393632)
$color4 = rgb(673A1D)
$color5 = rgb(625A53)
$color6 = rgb(A79B88)
$color7 = rgb(E7DFD2)
$color8 = rgb(A19C93)
$color9 = rgb(3F1810)
$color10 = rgb(494540)
$color11 = rgb(4D4843)
$color12 = rgb(894D27)
$color13 = rgb(83786F)
$color14 = rgb(DFCFB5)
$color15 = rgb(E7DFD2)
